KBBPUYCV	;JLI/JIVEYSOFT.COM - run coverage analysis ;04/28/17  18:54
	;;0.0;KBBP;;;
	;
	D RUNTHEM1(2)
	Q
	;
RUNTHEM(LEVEL,ROUTINES)	;
	N ROUNAMES,XCLDROUS,NAME
	S ROUNAMES(1)="KBBPUYNM,^KBBPYNM,^KBBPYQRY,^KBBPYDO1,^KBBPYROU,^KBBPYSHO,^KBBPYREL"
	S ROUNAMES(2)="^KBBPYSET,^KBBPYSE1,^KBBPYSE2,^KBBPYSH1,^KBBPYPRO,^KBBPYREF"
	S NAME=$S($D(ROUTINES):ROUTINES,1:"KBBPY*")
	D COVERAGE^%ut(NAME,.ROUNAMES,.XCLDROUS,LEVEL)
	Q
	;
RUNTHEM1(LEVEL,ROUTINES)	;
	N ROUNAMES,XCLDROUS,X,NAME
	S ROUNAMES(1)="KBBPUYNM,^KBBPYNM,^KBBPYQRY,^KBBPYDO1,^KBBPYROU,^KBBPYSHO"
	S ROUNAMES(2)="^KBBPYSET,^KBBPYSE1,^KBBPYSE2,^KBBPYSH1,^KBBPYPRO,^KBBPYREF"
	D COVERAGE^%ut("KBBPY*",.ROUNAMES,.XCLDROUS,LEVEL)
	Q
	;
KBBPYSHO	;
	N ROUNAMES,XCLDROUS
	S ROUNAMES(1)="EN^KBBPYSHO"
	D COVERAGE^%ut("KBBPY*",.ROUNAMES,.XCLDROUS,2)
	Q
	;
KBBPYQRY	;
	N %ut
	S %ut=1 ; make it look like inside a unit test
	N ROUNAMES,XCLDROUS
	S ROUNAMES(1)="EN^KBBPYQRY"
	D COVERAGE^%ut("KBBPY*",.ROUNAMES,.XCLDROUS,2)
	K %ut
	Q
	;
KBBPYROU	;
	N ROUNAMES,XCLDROUS
	S ROUNAMES(1)="EN^KBBPZ999"
	D COVERAGE^%ut("KBBPY*",.ROUNAMES,.XCLDROUS,2)
	Q
	;
1	;
	D RUNTHEM(1)
	Q
	;
3	;
	D RUNTHEM(3)
	Q
	;
ONEROU	;
	N ROUNAME,RUNROUS,XCLUDE,LEVEL
	Q:'$$GETINFO(.ROUNAME,.LEVEL)
	S RUNROUS(1)="KBBPUYNM"
	S RUNROUS(2)="^"_ROUNAME
	D COVERAGE^%ut(ROUNAME,.RUNROUS,.XCLUDE,LEVEL)
	Q
	;
GETINFO(ROUNAME,LEVEL)	; .EF - returns 1 if OK, 0 if should exit
	N X,Y
LOOP	;
	R !,"Enter Routine Name: ",ROUNAME:DTIME Q:(ROUNAME="")!(ROUNAME[U)!'$T 0
	W !,"Entered ",ROUNAME," - Is this correct? Y// " R Y:DTIME I Y'="","Yy"'[$E(Y,1) G LOOP
	S LEVEL=2
	R !,"Level: 2// ",X:DTIME Q:'$T!(X[U) 0  I X'="" G:"123"'[X LOOP S LEVEL=X
	Q 1
EOR	;
